application: python-gezegeni
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /tasks/update
  script: lib/update.py
  login: admin

- url: .*
  script: main.py